* Astro Starter Kit: Minimal

#+begin_src sh
npm create astro@latest -- --template minimal
#+end_src

*Seasoned astronaut?* Delete this file. Have fun!

** Project Structure

Inside of your Astro project, you'll see the following folders and files:

#+begin_src text
/
├── public/
├── src/
│   └── pages/
│       └── index.astro
└── package.json
#+end_src

Astro looks for =.astro= or =.md= files in the =src/pages/= directory. Each page is exposed as a route based on its file name.

There's nothing special about =src/components/=, but that's where we like to put any Astro/React/Vue/Svelte/Preact components.

Any static assets, like images, can be placed in the =public/= directory.

** Commands

All commands are run from the root of the project, from a terminal:

| Command                   | Action                                       |
|---------------------------+----------------------------------------------|
| =npm install=             | Installs dependencies                        |
| =npm run dev=             | Starts local dev server at =localhost:4321=  |
| =npm run build=           | Build your production site to =./dist/=      |
| =npm run preview=         | Preview your build locally, before deploying |
| =npm run astro ...=       | Run CLI commands like =astro add=, =astro check= |
| =npm run astro -- --help= | Get help using the Astro CLI                 |

** Want to learn more?

Feel free to check [[https://docs.astro.build][our documentation]] or jump into our [[https://astro.build/chat][Discord server]].
